---
- hosts: localhost
  gather_facts: no
  module_defaults:
    group/aws:
      #profile: auburn
      region: "us-east-2"
  vars:
    pg_secret: {
      "username": "postgres",
      "password": "v^l!o|EjMH?LM6.JkbV3`86(.D^4?)8w",
      "engine": "postgres",
      "host": "{{ rds.instance.endpoint }}",
      "port": 5432,
      "dbInstanceIdentifier": "m5-ig-rds",
      "database_name": "image_gallery"
    }

    imagegallery_secret: {
      "username": "image_gallery",
      "password": "simple",
      "engine": "n,|gRz$#_Bc&EmAjyI)t[j3vCv^4ty4n",
      "host": "{{ rds.instance.endpoint }}",
      "port": 5432,
      "dbInstanceIdentifier": "m5-ig-rds",
      "database_name": "image_gallery"
    }

  tasks:
    - name: Create Secrets Manager for Postgres User
      aws_secret:
        name: 'postgres-secret-m5'
        state: present
        secret_type: 'string'
        description: M5 postgres user
        secret: "{{ pg_secret | to_json }}"

    - name: Create Secrets Manager for Image Gallery User
      aws_secret:
        name: 'image_gallery-secret-m5'
        state: present
        secret_type: 'string'
        description: M5 image_gallery user
        secret: "{{ imagegallery_secret | to_json }}"

    # Create Lambda functions for rotation
    # - name: Create lambda for postgres
    #   lambda:
    #     name: m5-postgres-lambda
    #     state: present
    #     zip_file: '{{ item.zip_file }}'
    #     runtime: 'python2.7'
    #     role: 'arn:aws:iam::987654321012:role/lambda_basic_execution'
    #     handler: 'hello_python.my_handler'
    #     vpc_subnet_ids:
    #     - subnet-123abcde
    #     - subnet-edcba321
    #     vpc_security_group_ids:
    #     - sg-123abcde
    #     - sg-edcba321
    #     environment_variables: '{{ item.env_vars }}'
    #     tags:
    #       key1: 'value1'
    #   loop:
    #     - name: HelloWorld
    #       zip_file: hello-code.zip
    #       env_vars:
    #         key1: "first"
    #         key2: "second"
    #     - name: ByeBye
    #       zip_file: bye-code.zip
    #       env_vars:
    #         key1: "1"
    #         key2: "2"