---
- hosts: tag_Module_5
  user: ec2-user
  become: true
  vars: 
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Install emacs
      package:
        name: emacs-nox
        state: present
- hosts: tag_Department_DevOps
  user: ec2-user
  become: true
  vars: 
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Remove nano
      package:
        name: nano
        state: absent
