---
- hosts: localhost
  gather_facts: no
  vars:
    ami_id: "ami-026dea5602e368e96"
  module_defaults:
      group/aws:
        #profile: auburn
        region: "us-east-2"
  tasks:
    - name: Provision EC2 instance for Bob
      ec2: 
        key_name: auburnec2
        group: Module5-developer-sg
        instance_type: t3.nano
        image: "{{ ami_id }}"
        instance_tags:
          Name: Module5 Bob
          Module: 5
          Department: Accounting
        wait: yes
        vpc_subnet_id: "{{ public_subnet.subnet.id }}"
        assign_public_ip: yes
        exact_count: 1
        count_tag:
          Name: Module5 Bob

    - name: Provision EC2 instance for Mary
      ec2: 
        key_name: auburnec2
        group: Module5-developer-sg
        instance_type: t3.nano
        image: "{{ ami_id }}"
        instance_tags:
          Name: Module5 Mary
          Module: 5
          Department: Accounting
        wait: yes
        vpc_subnet_id: "{{ public_subnet.subnet.id }}"
        assign_public_ip: yes
        exact_count: 1
        count_tag:
          Name: Module5 Mary